# Generated by Django 5.1.7 on 2025-04-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinussubmission',
            name='full_name',
        ),
        migrations.AddField(
            model_name='joinussubmission',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='joinussubmission',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
